---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
DISABLE:
  - PYTHON
  - COPYPASTE
  - CSS
DISABLE_LINTERS:
  - SPELL_CSPELL
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: true
RST_FILTER_REGEX_EXCLUDE: "(:resource:`.+`)"
ACTION_ACTIONLINT_ARGUMENTS: "-ignore spellcheck"
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
---