person:
sun:
api:
timer:
input_number:
input_boolean:
input_datetime:
input_text:
logbook:
history:
trace:
counter:
tag:
notify:

logger:
  default: info

http:
  trusted_proxies:
    - 127.0.0.1
  use_x_forwarded_for: true
