#!/usr/bin/env bash

echo Installing Dependencies
sudo apt-get -qq install -y python3 python3-dev python3-venv python3-pip libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0-dev tzdata

echo Setting Up Server Directory
python -m venv test_server
. test_server/bin/activate

echo Copying Over Control Configuration
mkdir test_server/config
cp tests/server_config.yaml test_server/config/configuration.yaml

echo Installing Homeassistant
python -m pip install wheel setuptools --quiet
python -m pip install homeassistant --quiet

echo Starting Homeassistant
hass -c test_server/config

echo Zipping Folder
zip "tests/homeassistant_$(cat test_server/config/.HA_VERSION).zip" -r test_server/config


