name: Code Standards
on:
  push:
    paths:
      - "**.py"
  pull_request:
    branches:
      - master
      - dev
    paths:
      - "**.py"
  workflow_dispatch:

jobs:
  code_styling:
    name: "Code Styling"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install --with styling
      - name: Run Ruff
        run: poetry run ruff homeassistant_api
      - name: Run MyPy
        run: poetry run mypy homeassistant_api --show-error-codes

  code_functionality:
    name: "Code Functionality"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Pre Docker Setup
        run: |
          mkdir volumes/coverage
      - name: Run Test Environment
        run: |
          docker compose up --build --exit-code-from tests
        env:
          HOMEASSISTANTAPI_TOKEN: ${{ secrets.HOMEASSISTANTAPI_TOKEN }}
      - name: Post Docker Setup
        run: |
          sudo chown -R $USER volumes
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v2
        with:
          files: ./volumes/coverage/coverage.xml
          fail_ci_if_error: true
          verbose: true
